# Generated by Django 6.0.5 on 2026-05-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoldMapImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fold_maps/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seismic3DParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=200, verbose_name='Параметр')),
                ('value', models.CharField(max_length=100, verbose_name='Значення')),
                ('unit', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Параметр 3D',
                'verbose_name_plural': 'Параметри 3D',
            },
        ),
    ]
