# Generated by Django 6.0.5 on 2026-05-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DensityVelocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('lithology', models.CharField(max_length=100)),
                ('depth_interval', models.CharField(max_length=50)),
                ('density', models.FloatField(help_text='×10³ кг/м³')),
                ('v_min', models.FloatField(blank=True, help_text='V min, м/с', null=True)),
                ('v_max', models.FloatField(blank=True, help_text='V max, м/с', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeologicalHorizon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Горизонт')),
                ('depth_min', models.IntegerField(verbose_name='Глибина min, м')),
                ('depth_max', models.IntegerField(verbose_name='Глибина max, м')),
                ('rock_type', models.CharField(max_length=200, verbose_name='Породи')),
                ('gas_present', models.BooleanField(default=True, verbose_name='Газоносний')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Газоносний горизонт',
                'verbose_name_plural': 'Газоносні горизонти',
            },
        ),
        migrations.CreateModel(
            name='TectonicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('map_image', models.ImageField(blank=True, upload_to='tectonic/')),
            ],
        ),
    ]
